### ISSUE TITLE
English words containing this character "’" are not in the data base

### ISSUE THREAD

**Issue by theRealProHacker** [rspeer/wordfreq#94]
I tokenized an English text that contained short forms like it’ll or you’ve and then got the word frequency for each token. However, for these short forms, the `zipf_freq()` function gave me a frequency of zero. 

Is this a problem with the character, the tokenizer or the data?

Windows 10, Python 3.9, wordfreq 2.5.0

**Comment by rspeer** [comment]
You're right. The word frequency database only uses straight quotes (`'`), so curly quotes (`’`) appear with zero frequency. I hadn't noticed this because I was running wordfreq on text that had passed through [ftfy][].

[ftfy]: https://github.com/rspeer/python-ftfy

It seems reasonable that one of the lossy things that the `lossy_tokenize` function should do is to uncurl quotes.

**Comment by rspeer** [comment]
Fixed in v2.5.1.
